version: '3'

services:
  postgresql-test:
    image: postgres
    container_name: pg-test
    ports:
      - "5401:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./postgres-dev.conf:/etc/postgresql/postgresql.conf
      - ./data/data-test:/var/lib/postgresql/data
      - ./schema-dev.sql:/docker-entrypoint-initdb.d/schema.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
