/**
 * This set of routes tests the schemas and typings
 * It is using the types generated by json2ts from the schemas
 */
import fp from 'fastify-plugin'
import QuerystringSchema from '../../../schemas/user-login.json'
import { QuerystringSchema as IQuerystringSchema } from '../../../typings/user-login'

export default fp(async (server) => {
  server.route<{ Querystring: IQuerystringSchema }>({
    url: '/login',
    logLevel: 'warn',
    method: ['GET', 'POST'],
    schema: { querystring: QuerystringSchema },
    preHandler: (request, reply, done) => {
      const { username } = request.query
      done(username !== 'admin' ? new Error('Must be admin') : undefined)
    },
    handler: async (request) => {
      const { username, password } = request.query
      return { username, password }
    },
  })
})
